import { Building2, Stethoscope, Heart, Brain, Bone, Eye, Activity, Users } from "lucide-react"

export const hospitals = [
  {
    id: "cmu-health-center",
    name: "PROMPT HEALTH CENTER : AMS",
    fullName: "PROMPT HEALTH CENTER : AMS , Chiang Mai University",
    icon: Building2,
    color: "from-blue-600 to-blue-700",
    description:
      "Prom Health Center, a branch of the Chiang Mai University Health Center, operates under the Clinical Medical Technology Service Center, Faculty of Associated Medical Sciences, CMU. Provides physical therapy, occupational therapy, assessment and promotion of child development.",
    location:
      "Health Center Building, Chiang Mai University, 239 Huay Kaew Road, Suthep Subdistrict, Mueang District, Chiang Mai Province 50200",
    phone: "0-5394-9325",
    hours: "จ.-ศ. 8:00-20:00 (กิจกรรมบำบัดเฉพาะ 8:00-19:00), วันหยุดราชการ 8:00-16:00, ส. 8:00-16:00, อา. ปิด",
    gps: "https://goo.gl/maps/rhTno3qG2KKD6ZUV9",
    image: "/cmu-health-center.jpeg",
  },
  {
    id: "prom-health-center",
    name: "PROMPTHEALTH CENTER",
    fullName: "ศูนย์บริการเทคนิคการแพทย์คลินิก คณะเทคนิคการแพทย์ มช.",
    icon: Stethoscope,
    color: "from-emerald-600 to-emerald-700",
    description: "บริการตรวจสุขภาพ ตรวจเลือด เอกซเรย์ กายภาพบำบัด",
    location: "110 ถ.อินทวโรรส ศรีภูมิ เมือง เชียงใหม่ 50200",
    phone: "0-5393-6027, 0-5393-5094",
    hours: "จ.-ศ. 8:00-16:30, ส. 8:00-12:00, อา. ปิด",
    gps: "https://goo.gl/maps/example2",
    image: "/prom-health-center.jpeg",
  },
  {
    id: "meechok-health-center",
    name: "ศูนย์สุขภาพชุมชนมีโชค",
    fullName: "ศูนย์สุขภาพชุมชนมีโชค อำเภอเมือง จังหวัดเชียงใหม่",
    icon: Building2,
    color: "from-teal-600 to-teal-700",
    description: "ศูนย์สุขภาพชุมชนที่ให้บริการตรวจรักษาทั่วไป และบริการรังสีวิทยา",
    location: "ตำบลศรีภูมิ อำเภอเมือง จังหวัดเชียงใหม่ 50200",
    phone: "0-5324-5678",
    hours: "จ.-ศ. 8:00-16:30, ส. 8:00-12:00, อา. ปิด",
    gps: "https://goo.gl/maps/meechok",
    image: "/meechok-health-center.jpeg",
  },
  {
    id: "lampang-health-center",
    name: "ศูนย์สุขภาพชุมชนลำปาง",
    fullName: "ศูนย์สุขภาพชุมชนลำปาง อำเภอเมือง จังหวัดลำปาง",
    icon: Building2,
    color: "from-amber-600 to-amber-700",
    description: "ศูนย์สุขภาพชุมชนที่ให้บริการตรวจรักษาทั่วไป และบริการรังสีวิทยา",
    location: "อำเภอเมือง จังหวัดลำปาง 52000",
    phone: "0-5422-1234",
    hours: "จ.-ศ. 8:00-16:30, ส. 8:00-12:00, อา. ปิด",
    gps: "https://goo.gl/maps/lampang",
    image: "/lampang-health-center.jpeg",
  },
  {
    id: "kadfarang-hangdong-health-center",
    name: "ศูนย์สุขภาพชุมชนกาดฝรั่งหางดง",
    fullName: "ศูนย์สุขภาพชุมชนกาดฝรั่งหางดง อำเภอหางดง จังหวัดเชียงใหม่",
    icon: Building2,
    color: "from-lime-600 to-lime-700",
    description: "ศูนย์สุขภาพชุมชนที่ให้บริการตรวจรักษาทั่วไป กายภาพบำบัด และรังสีวิทยา",
    location: "อำเภอหางดง จังหวัดเชียงใหม่ 50230",
    phone: "0-5344-5678",
    hours: "จ.-ศ. 8:00-16:30, ส. 8:00-12:00, อา. ปิด",
    gps: "https://goo.gl/maps/kadfarang",
    image: "/kadfarang-hangdong-health-center.png",
  },
  {
    id: "wellness-cmu-health-center",
    name: "ศูนย์สุขภาพเวลเนส มช.",
    fullName: "ศูนย์สุขภาพเวลเนส มหาวิทยาลัยเชียงใหม่",
    icon: Building2,
    color: "from-rose-600 to-rose-700",
    description: "ศูนย์สุขภาพเฉพาะทางสำหรับผู้สูงอายุ ให้บริการแพทย์ทั่วไปและแพทย์ผู้สูงอายุ",
    location: "มหาวิทยาลัยเชียงใหม่ ถนนห้วยแก้ว ตำบลสุเทพ อำเภอเมือง จังหวัดเชียงใหม่ 50200",
    phone: "0-5394-3210",
    hours: "จ.-ศ. 8:00-17:00, ส. 8:00-12:00, อา. ปิด",
    gps: "https://goo.gl/maps/wellness-cmu",
    image: "/wellness-cmu-health-center.jpeg",
  },
  {
    id: "suan-dok",
    name: "โรงพยาบาลศรีนครินทร์",
    fullName: "โรงพยาบาลศรีนครินทร์ คณะแพทยศาสตร์ มหาวิทยาลัยเชียงใหม่",
    icon: Building2,
    color: "from-red-600 to-red-700",
    description: "โรงพยาบาลมหาวิทยาลัย บริการครบครัน",
    location: "110 ถ.อินทวโรรส ศรีภูมิ เมือง เชียงใหม่ 50200",
    phone: "0-5394-5000",
    hours: "24 ชั่วโมง",
    gps: "https://goo.gl/maps/example3",
    image: "/suan-dok-hospital.jpeg",
  },
  {
    id: "sriphat",
    name: "โรงพยาบาลศรีพัฒน์",
    fullName: "โรงพยาบาลศรีพัฒน์ มหาวิทยาลัยเชียงใหม่",
    icon: Building2,
    color: "from-purple-600 to-purple-700",
    description: "โรงพยาบาลเฉพาะทาง บริการแพทย์เฉพาะทาง",
    location: "700 ถ.สุเทพ ศรีภูมิ เมือง เชียงใหม่ 50200",
    phone: "0-5393-6900",
    hours: "24 ชั่วโมง",
    gps: "https://goo.gl/maps/example4",
    image: "/sriphat-medical-center.jpeg",
  },
]

export const departments = [
  {
    id: "general",
    name: "แพทย์ทั่วไป",
    description: "บริการตรวจรักษาทั่วไป",
    icon: Stethoscope,
    color: "from-blue-500 to-blue-600",
  },
  {
    id: "cardiology",
    name: "หัวใจและหลอดเลือด",
    description: "ตรวจรักษาโรคหัวใจ",
    icon: Heart,
    color: "from-red-500 to-red-600",
  },
  {
    id: "internal",
    name: "อายุรกรรม",
    description: "โรคภายใน",
    icon: Activity,
    color: "from-green-500 to-green-600",
  },
  {
    id: "neurology",
    name: "ประสาทวิทยา",
    description: "โรคระบบประสาท",
    icon: Brain,
    color: "from-purple-500 to-purple-600",
  },
  {
    id: "orthopedics",
    name: "กระดูกและข้อ",
    description: "โรคกระดูกและข้อ",
    icon: Bone,
    color: "from-orange-500 to-orange-600",
  },
  {
    id: "ophthalmology",
    name: "จักษุวิทยา",
    description: "โรคตา",
    icon: Eye,
    color: "from-cyan-500 to-cyan-600",
  },
  {
    id: "geriatrics",
    name: "แพทย์ผู้สูงอายุ",
    description: "ดูแลผู้สูงอายุเฉพาะทาง",
    icon: Users,
    color: "from-indigo-500 to-indigo-600",
  },
  {
    id: "physical-therapy",
    name: "กายภาพบำบัด",
    description: "บำบัดฟื้นฟูสมรรถภาพ",
    icon: Activity,
    color: "from-teal-500 to-teal-600",
  },
  {
    id: "radiology",
    name: "รังสีวิทยา",
    description: "ตรวจเอกซเรย์และภาพถ่าย",
    icon: Activity,
    color: "from-gray-500 to-gray-600",
  },
  {
    id: "pediatrics",
    name: "กุมารแพทย์",
    description: "แพทย์เด็ก",
    icon: Users,
    color: "from-pink-500 to-pink-600",
  },
  {
    id: "emergency",
    name: "แพทย์ฉุกเฉิน",
    description: "บริการฉุกเฉิน 24 ชั่วโมง",
    icon: Activity,
    color: "from-red-500 to-red-600",
  },
]

export const hospitalDepartments = {
  "cmu-health-center": ["general", "physical-therapy", "pediatrics"],
  "prom-health-center": ["general", "physical-therapy", "radiology"],
  "meechok-health-center": ["general", "radiology"],
  "lampang-health-center": ["general", "radiology"],
  "kadfarang-hangdong-health-center": ["general", "physical-therapy", "radiology"],
  "wellness-cmu-health-center": ["general", "geriatrics"],
  "suan-dok": ["cardiology", "internal", "neurology", "orthopedics", "ophthalmology", "general", "emergency"],
  sriphat: ["cardiology", "internal", "neurology", "orthopedics", "ophthalmology", "general", "emergency"],
}

export const doctors = [
  {
    id: "dr-somchai",
    name: "นพ.สมชาย ใจดี",
    specialty: "แพทย์ทั่วไป",
    hospital: "cmu-health-center",
    department: "general",
    experience: "15 ปี",
    rating: "4.8",
    phone: "0-5394-9325",
    schedule: "จ.-ศ. 8:00-16:00",
    image: "/doctor-1.jpg",
  },
  {
    id: "dr-malee",
    name: "นพ.มาลี สุขใส",
    specialty: "กายภาพบำบัด",
    hospital: "cmu-health-center",
    department: "physical-therapy",
    experience: "12 ปี",
    rating: "4.9",
    phone: "0-5394-9326",
    schedule: "จ.-ศ. 8:00-19:00",
    image: "/doctor-2.jpg",
  },
  {
    id: "dr-prasert",
    name: "นพ.ประเสริฐ หัวใจแข็ง",
    specialty: "หัวใจและหลอดเลือด",
    hospital: "suan-dok",
    department: "cardiology",
    experience: "20 ปี",
    rating: "4.9",
    phone: "0-5394-5001",
    schedule: "จ.-ศ. 8:00-16:00",
    image: "/doctor-3.jpg",
  },
  {
    id: "dr-siriporn",
    name: "นพ.ศิริพร ใสใจ",
    specialty: "อายุรกรรม",
    hospital: "suan-dok",
    department: "internal",
    experience: "18 ปี",
    rating: "4.7",
    phone: "0-5394-5002",
    schedule: "จ.-ศ. 9:00-17:00",
    image: "/doctor-4.jpg",
  },
  {
    id: "dr-wichai",
    name: "นพ.วิชัย สมองใส",
    specialty: "ประสาทวิทยา",
    hospital: "sriphat",
    department: "neurology",
    experience: "22 ปี",
    rating: "4.8",
    phone: "0-5393-6901",
    schedule: "จ.-ศ. 8:00-16:00",
    image: "/doctor-5.jpg",
  },
]

export const availableDates = [
  {
    date: "2024-01-15",
    display: "วันจันทร์ที่ 15 มกราคม 2567",
    available: true,
  },
  {
    date: "2024-01-16",
    display: "วันอังคารที่ 16 มกราคม 2567",
    available: true,
  },
  {
    date: "2024-01-17",
    display: "วันพุธที่ 17 มกราคม 2567",
    available: false,
  },
  {
    date: "2024-01-18",
    display: "วันพฤหัสบดีที่ 18 มกราคม 2567",
    available: true,
  },
  {
    date: "2024-01-19",
    display: "วันศุกร์ที่ 19 มกราคม 2567",
    available: true,
  },
  {
    date: "2024-01-22",
    display: "วันจันทร์ที่ 22 มกราคม 2567",
    available: false,
  },
  {
    date: "2024-01-23",
    display: "วันอังคารที่ 23 มกราคม 2567",
    available: true,
  },
]

export const timeSlots = [
  { time: "08:00", available: true },
  { time: "08:30", available: true },
  { time: "09:00", available: false },
  { time: "09:30", available: true },
  { time: "10:00", available: true },
  { time: "10:30", available: false },
  { time: "11:00", available: true },
  { time: "11:30", available: true },
  { time: "13:00", available: true },
  { time: "13:30", available: false },
  { time: "14:00", available: true },
  { time: "14:30", available: true },
  { time: "15:00", available: true },
  { time: "15:30", available: false },
  { time: "16:00", available: true },
  { time: "16:30", available: true },
]
